{{- if eq .Values.secrets.useExisting false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name}}
  labels:
    {{- include "mssql-latest.labels" . | nindent 4 }}
type: Opaque
data:
 sa_password : {{ .Values.secrets.sa_password | b64enc | quote}}
{{- end }}